### ISSUE TITLE
Sync .jshintrc with Apontador JS style guide

### ISSUE THREAD

**Issue by heldr** [apontador/teco-js#5]
We must auto sync Teco-js .jshintrc with [Apontador javascript style](https://github.com/apontador/javascript)

I tried with this approach:

``` js
shell: {
    jshintrc_sync: {
        command: 'curl -0 https://raw.github.com/apontador/javascript/master/.jshintrc > .jshintrc',
        options: {
            stdout: false
        }
    },
    bower: {
        command: 'node_modules/.bin/bower install',
        options: {
            stdout: true
        }
    }
}
```

but it breaks because JSON doesn't support comments and removing it we get more than hundred warnings.

**Comment by renanivo** [comment]
I think we have to remove the comments (I just copied some flags from the SublimeLinter and kept the comments) and fix the teco-js warnings. Let's make a branch for that.

**Comment by heldr** [comment]
"a long time ago in a far far galaxy..."

**Comment by renanivo** [comment]
![Thank You!](https://media.giphy.com/media/wMY3LjQQMqo5W/giphy.gif)
